### ISSUE TITLE
Upgrade our Nvidia Jetson AGX Orin to JetPack 6 and ISAAC ROS 3.1

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#154]
Completed Tasks:
-Upgrade the Jetson AGX Orin from Jetpack 5 to Jetpack 6
-Finish updating our codebase to Isaac ROS 3.1 (There is a branch for this [here](https://github.com/GOFIRST-Robotics/Lunabotics/tree/move-to-isaac-ros-3.1))
-Test the devcontainer on both windows and mac to make sure we didn't break it (Anthony is doing this)
-Test everything to make sure it is working on both x86 and Jetson! (including rqt camera streamer, svo playback, and live zed on Jetson!)

**Comment by Isopod00** [comment]
> Also use ubuntu 24.04 to support Jazzy

I'm not sure if this is possible now that I think about it? JetPack 6.0 is based on Ubuntu 22.04, not Ubuntu 24.04. Nvidia is always like 2 years behind the latest Ubuntu version lol, currently we use Ubuntu 20.04

**Comment by jmblixt3** [comment]
Triton server was built with small patches found in my repo which were upstreamed. 
Rosdep appears to be real rough rn so we're going to wait longer for that to mature

**Comment by jmblixt3** [comment]
Zed won't support 24.04, so stick to humble

**Comment by jmblixt3** [comment]
On hold for zed to be readded to nvblox
