### ISSUE TITLE
Test our code with the ThriftyBot Absolute Encoders and add a calibration offset variable for each module

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics#158]
We have received absolute encoders, now it's time to test them with our code

**Comment by Isopod00** [comment]
I think we also still need to add a calibration_offset variable for each module, this will be a constant variable for each module that defines an offset based on how the magnets are oriented in the shafts (we will need to determine the values for these offset variables after the real robot is completed, this will be our initially calibration of the swerve modules and then after these offsets are configured we should never need to calibrate the modules again)
