### ISSUE TITLE
Team Desktop Setup

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics#18]
- Add Ubuntu dual boot and ROS to both desktops (Done)
- Install vscode, git, clone our repository and make sure it builds (Done)
- Add Nvidia docker setup (Not possible without an Nvidia GPU)

**Comment by Isopod00** [comment]
Ubuntu dual boot has been added to both Snowplow desktops

**Comment by umnrobotics** [comment]
Git VScode, and ROS have been installed on both

**Comment by umnrobotics** [comment]
I realized that we cannot install CUDA on the snowplow desktops since they don't have Nvidia GPUs
