### ISSUE TITLE
Find optimal heights for the 2 static map slices

### ISSUE THREAD

**Issue by BergerKing333** [GOFIRST-Robotics/Lunabotics#187]
Combining the static map slices seems to be working, however, we need to mess with different heights using different recordings to see how that affects the final slice. Need another/ a better recording first though

**Comment by Isopod00** [comment]
@BergerKing333 What's the status of this ticket? Is this included in your current nvblox PR, or no?

**Comment by BergerKing333** [comment]
> [@BergerKing333](https://github.com/BergerKing333) What's the status of this ticket? Is this included in your current nvblox PR, or no?

No, this is more along the lines of testing the realsense dirt collection; all that needs to happen is editing 2 numbers in a config but kinda need the robot to test with to find the correct numbers to set to.

**Comment by BergerKing333** [comment]
Also, mess with configs for the above ground denoising and the inflation layer configuration. need good/official recording before messing with these

**Comment by jmblixt3** [comment]
This will need some adjustment for current recordings due to adjustments in the base_link transforms
