### ISSUE TITLE
Write a launch script to record match data (record a zed svo file)

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics#189]
Make sure this is reasonably polling topics so it is a reasonable size...

**Comment by Isopod00** [comment]
Look at this as an example but we should probably record an svo instead of a rosbag: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nvblox/blob/main/nvblox_examples/nvblox_examples_bringup/launch/sensors/record_realsense.launch.py
