### ISSUE TITLE
Replace all instances of "skimmer" in our project with "digger" to match the new subsystem name

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#288]
Use the magnifying glass in VSCode to search our project for all instances of "skimmer".

Notes:
-Make sure to still follow the proper/existing case/capitalization of variables!
-Don't modify any of the urdf or csv files for the simulated robot model (it is an old model that we will be replacing anyways)

**Comment by Brijeshthummar02** [comment]
i can do this, assign me.
