### ISSUE TITLE
Record an SVO2 file with gen2 position tracking

### ISSUE THREAD

**Issue by BergerKing333** [GOFIRST-Robotics/Lunabotics#309]
Our old SVO files are messed up because we were using a bad .urdf file when we recorded them. In the old svo files, the ground renders at an angle which makes it hard to test with. They've also released SVO2 files since then. 
For this task, go out to the sandpit behind Shepard Labs, dig a small hole, create a small hill, and record a new SVO2 with the zed, walking around the hole/hill.

**Comment by Isopod00** [comment]
I started [this](https://github.com/GOFIRST-Robotics/Lunabotics/tree/Record-an-SVO2-file) branch for this.
