### ISSUE TITLE
Automatically configure a nice linting setup in our dev container

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#33]
DONE:
-**For Python:** Black auto-formatter and Ruff linter
-**For C++:** SonarLint and the built-in c++ formatter

**Comment by Isopod00** [comment]
SonarLint and Black are installed in our dev container but aren't currently configured automatically. Furthermore, we should use the new Ruff linter for Python because it's fancier (it's built in Rust and runs very fast!)

**Comment by jmblixt3** [comment]
Also make sure that line endings are normalized see https://github.com/GOFIRST-Robotics/Lunabotics-2024/pull/36#discussion_r1317778848
