### ISSUE TITLE
Bring up our 2024 robot inside of gazebo

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/Lunabotics#55]

**Comment by jmblixt3** [comment]
http://wiki.ros.org/sw_urdf_exporter/Tutorials/Export%20an%20Assembly
This is for ros1 but someone made this
https://github.com/xiaoming-sun6/sw2urdf_ros2

**Comment by jmblixt3** [comment]
Make sure to add tf's from zed to robot base

**Comment by Isopod00** [comment]
We should export our current CAD model as a URDF file for gazebo

**Comment by Isopod00** [comment]
I started messing around with creating a moon Gazebo world in this branch: https://github.com/GOFIRST-Robotics/Lunabotics-2024/tree/gazebo-testing
