### ISSUE TITLE
Fix setup tools in devcontainer

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#60]
add this 
```PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"; export PYTHONWARNINGS```

**Comment by Isopod00** [comment]
@jmblixt3 are you sure that ignoring this warning is the solution? Previously I thought the solution was to downgrade setup_tools.py to the "proper" version.

**Comment by Isopod00** [comment]
actually now that I look at it I think both of these are just workarounds, the real solution is probably to just make the changes it wants: [thread](https://answers.ros.org/question/386341/ros2-userwarning-usage-of-dash-separated-install-scripts-will-not-be-supported-in-future-versions-please-use-the-underscore-name-install_scripts/#:~:text=According%20to%20this%20link%3A%20https%3A%2F%2Fanswers.ros.org%2Fquestion%2F3964...%20The%20reason%20is,install%20setuptools%3D%3D58.2.0%20and%20it%20shows%20no%20warnings%20anymore.)

**Comment by jmblixt3** [comment]
You can fix one of the issues like thos but others are unfixable due to ros
build system

**Comment by jmblixt3** [comment]
https://github.com/ament/ament_cmake/issues/382#issuecomment-1528083515
