### ISSUE TITLE
Fix these setuptool deprecations after we upgrade to the new Jetpack

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#63]
1.) UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
2.) UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
3.) EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.

**Comment by jmblixt3** [comment]
This has been fixed by nvidia
