### ISSUE TITLE
Experiment with using a RealSense (depth camera) to determine the amount of regolith on the conveyor belt

### ISSUE THREAD

**Issue by Isopod00** [GOFIRST-Robotics/Lunabotics#67]
Let's also utilize the video from this RealSense to give us an internal view of the robot!

Currently working in this branch: https://github.com/GOFIRST-Robotics/Lunabotics-2024/tree/realsense-wrapper-test

**Comment by BergerKing333** [comment]
we got cv2 installed and have the code to do a gaussian blur/denoise the image, just need to test. Also, need to check, but using cv.imgshow might allow us to see the picture that we're working with when we are ssh-ed

**Comment by Isopod00** [comment]
We may need to implement dynamic cropping of some kind unless we can mount the realsense so that it moves up and down with the conveyor. We should ask mechanical if mounting it to move with the conveyor would be possible. It needs to be mounted high enough to avoid noisy readings.
